### ISSUE TITLE
在线等一个big sur测试

### ISSUE THREAD

**Issue by OysterQAQ** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#114]
大佬们 是否可以用啊

**Comment by FFzt** [comment]
> 大佬们 是否可以用啊
你可以试一下 然后告诉我们

**Comment by hforlong** [comment]
观望一下

**Comment by fg4084** [comment]
MARK
Common issues have included graphical issues like problems with external display support, apps freezing, and random reboots. Stability has improved over the course of the beta period and Apple had longer this year with macOS Big Sur launching in November instead of September or October, but bugs and performance issues aren’t totally resolved yet.

**Comment by wangxin00320** [comment]
可以用，但是我手贱了下现在不行了。。。

**Comment by hforlong** [comment]
0.6.3直接升级的，目前好像没有啥问题，再用用看。

**Comment by ghost-yuanye** [comment]
我也是0.6.3直接升级～目前没毛病～

**Comment by yansh15** [comment]
0.6.3全新安装，没有遇到问题。

**Comment by GeQ1an** [comment]
没有大问题，但可能会有一些随机的小问题，比如我遇到了随机突发性黑屏。如果不是非常着急体验，建议等等 OC 0.6.4 及 kexts 更新或 macOS 11.1 正式版。

**Comment by fg4084** [comment]
已升级，只遇到了系统的问题：菜单栏图标位置不能保存

**Comment by OysterQAQ** [comment]
感谢各位🙏等下一个版本的oc吧还是
